### ISSUE TITLE
The ServiceStack.Redis library being used is a commercial product with free use limitations

### ISSUE THREAD

**Issue by JustinC-iQmetrix** [RyanMarcotte/Functional.CQS#19]
`Functional.CQS.AOP.Caching.Infrastructure.DistributedCache.Redis` is using the [ServiceStack.Redis](https://github.com/ServiceStack/ServiceStack.Redis) library which is a commercially licensed product with free use limitations. Documented [here](https://servicestack.net/download#free-quotas).

A popular alternative to `ServiceStack` is the [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis) library which is released under an MIT licence and is still being actively supported.

**Comment by RyanMarcotte** [comment]
That's an oversight on my part.  Since the intent is for this library to remain free under the MIT license, this change is necessary.  Stay tuned!

**Comment by RyanMarcotte** [comment]
I ran into a snag when deploying the new version of the package...  I forgot to transfer ownership of all `Functional.CQS` packages to my personal NuGet.org account.  I'll let you know when it's finally uploaded @JustinC-iQmetrix .

**Comment by RyanMarcotte** [comment]
Just uploaded the package now @JustinC-iQmetrix .  It should show up in NuGet search results within the next 15-30 minutes or so.

**Comment by JustinC-iQmetrix** [comment]
That's great, thanks for the update!
