### ISSUE TITLE
Update all packages to use Functional v2.0 once it has been released

### ISSUE THREAD

**Issue by RyanMarcotte** [RyanMarcotte/Functional.CQS#21]
Once https://github.com/JohannesMoersch/Functional/pull/82 is merged and the v2.0 package is published, update all `Functional.CQS` packages to use v2.0

**Comment by willikev** [comment]
This task is now unblocked, as non-beta v2.0.0 versions of https://www.nuget.org/packages/Functional.All/2.0.0 and its dependencies were all published yesterday afternoon.

**Comment by RyanMarcotte** [comment]
Packages are now available @willikev
